# Generated by Django 4.0.5 on 2022-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.CharField(blank=True, choices=[('', 'No contract'), ('12', '12 Months')], max_length=25, null=True),
        ),
    ]
